### ISSUE TITLE
Get python dataclasses / classes from ObjectType

### ISSUE THREAD

**Issue by nettrino** [mirumee/ariadne-graphql-modules#11]
Is it possible to generate python objects (e.g., dataclasses) from a given gql definition using the already available 'graphql_fields` etc attributes? Essentially looking to parse a graphql file and then have equivalent python objects available so that they can be used within the codebase in sync with the schema.

**Comment by rafalp** [comment]
I don't see why it shouldn't be. `__schema__` attribute contains everything that's needed for such conversion:

- type name
- fields names
- fields types

You would only need to inspect GraphQL's AST produced by object's parsing, but speaking from experience that's quite easy to do.

**Comment by nettrino** [comment]
Thanks for the prompt reply @rafalp. I see this related request here - https://github.com/mirumee/ariadne/discussions/509 and seems this would be a most useful feature for any python project working with graphql, as one would be able to have the type part of the codebase autogenerated as needed

**Comment by rafalp** [comment]
My problem with this approach (and part of reason why we've didn't do this) is that it's really complex issue when you start to dig into it.

If you have schema like this:

```
type Query {
    users: [User!]!
}

type User {
    id: ID!
    name: String!
    fullName: String!
    posts: [Post!]!
}

type Post {
    id: ID!
    text: String!
}
```

You will probably generate types like this:

```python
class Post:
    id: id
    text: str

class User:
    id: id
    name: str
    fullName: str
    posts: [Post!]

class Query:
    users: list[User]

def resolve_users(*_) -> list[User]:
    ...
```

You now need to return everything from `resolve_users`, which results in overfetching. To avoid this you will have to mark all types fields as optional, which takes away the benefit of having resolved data match the schema.

**Comment by nettrino** [comment]
I understand - also there exists the problem of circular imports. I will give https://github.com/sauldom102/gql_schema_codegen a try now but anything I don't need to build from scratch is welcome :)

**Comment by rafalp** [comment]
>  I don't need to build from scratch is welcome

Not the problem you have, but we are building GraphQL codegen for python that takes bunch of GraphQL queries and gives you fully typed GraphQL client for those queries.

**Comment by rafalp** [comment]
I'll close this issue because its kinda out of scope for Ariadne GraphQL Modules, but there are ideas for extra consistency checks between resolvers and schema that we could add in future.
