### ISSUE TITLE
File upload

### ISSUE THREAD

**Issue by Ivan8R** [mirumee/ariadne-graphql-modules#31]
Is it possible to make file upload  with ariadne-graphql-modules? If yes what is the implementation? if no is it possible use approach from ariadne with scalar "upload"?
Thank you

**Comment by rafalp** [comment]
Uploads only require that schema contains `scalar Upload`. There's no need for any custom logic on this scalar, so it should be possible to do:

```python
class UploadScalar(ScalarType):
    __schema__ = "scalar Upload"
```

**Comment by Ivan8R** [comment]
Thank you.
