### ISSUE TITLE
Support ariadne >= 0.22

### ISSUE THREAD

**Issue by intellisense** [mirumee/ariadne-graphql-modules#35]
The package `ariadne` in version [0.22](https://github.com/mirumee/ariadne/blob/main/CHANGELOG.md#022-2024-01-31) introduced some breaking changes:

  > Removed validate_schema_enum_values and introduced validate_schema_default_enum_values in its place. This is a breaking change.

  > `ariadne.enums.set_default_enum_values_on_schema` is removed.

The current requirement isn't restricted [here](https://github.com/mirumee/ariadne-graphql-modules/blob/main/pyproject.toml#L25).
https://github.com/mirumee/ariadne-graphql-modules/blob/a3381b7b195b0935f7840da35ddda9a132a0bbce/pyproject.toml#L25

**Comment by rafalp** [comment]
I've released Ariadne GraphQL Modules 0.8 with support for Ariadne 0.22

**Comment by intellisense** [comment]
Thank you for the quick resolution.
