### ISSUE TITLE
make_executable_schema Camel case args

### ISSUE THREAD

**Issue by bszema** [mirumee/ariadne-graphql-modules#41]
i have sth like this articles(first: Int!, after: ID, isFeatured: Boolean): ArticleCollection!

in resolvers code i must have sth like this:
@staticmethod
def resolve_articles(
category: CategoryProxy,
info: GraphQLResolveInfo,
first: int,
after: str | None = None,
isFeatured: bool | None = None,
):

i Would prefere to have this as python case

desirable resolver should look like this

@staticmethod
def resolve_articles(
category: CategoryProxy,
info: GraphQLResolveInfo,
first: int,
after: str | None = None,
is_featured: bool | None = None,
):

**Comment by rafalp** [comment]
https://github.com/mirumee/ariadne-graphql-modules/blob/main/REFERENCE.md#converting-fields-arguments

**Comment by DamianCzajkowski** [comment]
@bszema Is this solved your issue?
